### PR TITLE
Fix Reparenting - SelectionState Stores EntityUUIDs

### LINKED ISSUE #9645: [Bug]: Reparenting Entities in Studio Hierarchy Panel Breaks UI
### Version

0f27df2(1.5.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### Browser (if applicable)

_No response_

### What is supposed happened?

Reparent should occur when a hierarchy node is dragged onto another hierarchy node.

### What happened?

When a hierarchy node is dragged onto another hierarchy node, the UI crashes with no errors

### Steps to reproduce

```shell
1. Open any scene in the studio
2. Drag any hierarchy node onto any other hierarchy node to attempt a reparent
3. UI crashes
```

### Relevant Info

_No response_

### PR DESCRIPTION
**Pull request by HexaField**
## Summary

fixes reparenting suspending UI

## References
closes #9645

### CODE REVIEW

**Review by dinomut1 — CHANGES_REQUESTED** [review]
Running into a crash when chaining reparents
[Screencast from 01-31-2024 01:59:08 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/9a761c21-b1e1-45fa-884d-c74f52b89dca)

**Review by dinomut1 — CHANGES_REQUESTED** [review]
[Screencast from 02-02-2024 03:02:35 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/0c349d4d-f4a1-4800-869c-d2e364ef0c48)
I'm not able to select things now. Reparenting and stuff works, but the properties panel is not showing selection

**Comment by HexaField** [comment]
> [Screencast from 02-02-2024 03:02:35 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/0c349d4d-f4a1-4800-869c-d2e364ef0c48) I'm not able to select things now. Reparenting and stuff works, but the properties panel is not showing selection

resolved

File: packages/editor/src/components/element/PropertiesPanelContainer.tsx [hunk 1]
```diff
@@ -106,25 +111,14 @@ const EntityEditor = (props: { entity: Entity; multiEdit: boolean }) => {
  * PropertiesPanelContainer used to render editor view to customize property of selected element.
  */
 export const PropertiesPanelContainer = () => {
-  const selectionState = useHookstate(getMutableState(SelectionState))
-  const editorState = useHookstate(getMutableState(EditorState))
-  const entity = useHookstate<Entity>(UndefinedEntity)
-  const multiEdit = useHookstate<boolean>(false)
+  const selectedEntities = useHookstate(getMutableState(SelectionState).selectedEntities).value
```
Comment (DanielBelmes) [inline packages/editor/src/components/element/PropertiesPanelContainer.tsx:114]: ~~can remove UseHookstate here since it's not used in the useEffect anymore and we're just using its value.~~ Sorry I think it's good as the component will rerender if selectedEntities changes.

**Review by the-reality-engineer — APPROVED** [review]
