### PR TITLE
Resource State

### LINKED ISSUE #9535: Reference Counting for disposable threejs objects

### LINKED ISSUE #9629: Create ResourceManagerState
Part of Resource Manager Epic [#9613](https://github.com/EtherealEngine/etherealengine/issues/9613)

### LINKED ISSUE #9674: Update MeshBVH Package Version
### Version

0f27df2(1.5.0)

### Operating Systems

- [X] macOS
- [X] Windows
- [X] Linux
- [X] Android
- [X] IOS

### Browser (if applicable)

_No response_

### What is supposed happened?

look at: https://github.com/gkjohnson/three-mesh-bvh

### What happened?

Not applicable

### Steps to reproduce

```shell
Use editor
```

### Relevant Info

_No response_

### PR DESCRIPTION
**Pull request by MichaelEstes**
## Summary
Resource Manager and State
## References
closes #9629 
closes https://github.com/EtherealEngine/etherealengine/issues/9535
closes https://github.com/EtherealEngine/etherealengine/issues/9674

### CODE REVIEW

File: packages/engine/src/assets/state/ResourceState.ts [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+  metadata: {
+    size?: number
+  }
+  onGPU: boolean
+}
+
+export const ResourceState = defineState({
+  name: 'ResourceManagerState',
+  initial: () => ({
+    resources: {} as Record<string, Resource>
```
Comment (the-reality-engineer) [inline packages/engine/src/assets/state/ResourceState.ts]: Let's maintain a separate record for each type of resource so that we can hold different metadata for different kinds of things.

File: packages/engine/src/assets/functions/resourceHooks.ts [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+      (request) => {
+        if (!unmounted) progress.set(request)
+      },
+      (err) => {
+        if (!unmounted) error.set(err)
+      }
+    )
+
+    return () => {
+      unmounted = true
```
Comment (the-reality-engineer) [inline packages/engine/src/assets/functions/resourceHooks.ts]: We should use an AbortController to cancel fetching resources here

File: packages/engine/src/assets/state/ResourceState.ts [hunk 3]
```diff
@@ -0,0 +1,246 @@
...
+  const resources = resourceState.nested('resources')
+  if (!resources[url].value) {
+    console.error('ResourceManager:unload No resource exists for url: ' + url)
+    return
+  }
+
+  const resource = resources[url]
+
+  resource.references.set((entities) => {
+    const index = entities.indexOf(entity)
```
Comment (the-reality-engineer) [inline packages/engine/src/assets/state/ResourceState.ts:368]: We should be performing reference counting here; a single entity may use the same resource more than once.

**Review by the-reality-engineer — CHANGES_REQUESTED** [review]

File: packages/engine/src/assets/functions/resourceHooks.ts [hunk 4]
```diff
@@ -31,6 +31,16 @@ import { LoadingArgs } from '../classes/AssetLoader'
 import { GLTF } from '../loaders/gltf/GLTFLoader'
 import { AssetType, ResourceManager, ResourceType } from '../state/ResourceState'
 
+function getAbortController(url: string, callback: () => void): AbortController {
```
Comment (HexaField) [inline packages/engine/src/assets/functions/resourceHooks.ts]: this should be called `createAbortController` since it creates one

File: packages/engine/src/assets/state/ResourceState.ts (hunk 1 above)
Comment (MichaelEstes) [reply packages/engine/src/assets/state/ResourceState.ts]: I added this in, but then removed it because some hooks from Three js are helpful in determining the loading state, but they only pass the url of the asset. Having different metadata types for each asset type is still implemented, but through a discriminated union approach instead of separate records.

**Comment by DanielBelmes** [comment]
Have put up on QAT to smoke test. Looking good!

**Review by DanielBelmes — APPROVED** [review]

**Review by HexaField — APPROVED** [review]
