### PR TITLE
9850-bug-reparenting-broken-in-studio

### LINKED ISSUE #9850: [Bug]: Reparenting Broken in Studio
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### Browser (if applicable)

_No response_

### What is supposed happened?

Not applicable

### What happened?

Reparent causes UI to go blank, need to close and re-open to see that the reparent has occurred, but all descendants of the newly reparented model are missing.
[Screencast from 03-06-2024 05:07:29 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/a956e430-b6a0-42a5-ba67-ed3f652f4c11)

### Steps to reproduce

```shell
For UI bug, reparent anything in the hierarchy panel. When reparenting a model, the geo will be missing
```

### Relevant Info

_No response_

### PR DESCRIPTION
**Pull request by SYBIOTE**
## Summary
reparenting was broken because momentarily changing the entity id causes the Name component used in nameInputGroup to lose context causing a block

## References
closes #9850

### CODE REVIEW

File: packages/editor/src/components/properties/NameInputGroup.tsx [hunk 1]
```diff
@@ -54,14 +54,14 @@ const styledNameInputGroupStyle = {
  * @type {class component}
  */
 export const NameInputGroup: EditorComponentType = (props) => {
-  const nameComponent = useComponent(props.entity, NameComponent)
-
+  const nameComponent = useOptionalComponent(props.entity, NameComponent)
```
Comment (HexaField) [inline packages/editor/src/components/properties/NameInputGroup.tsx:57]: Can we figure out instead why the name input group is being rendered?

Comment (SYBIOTE) [reply packages/editor/src/components/properties/NameInputGroup.tsx:57]: It's being rendered in the properties panel?

Comment (HexaField) [reply packages/editor/src/components/properties/NameInputGroup.tsx:57]: Yeah, but I see your comment in the issue so this is fine

**Review by HexaField — APPROVED** [review]
